name: flutter_fortune_slip
description: "おみくじアプリ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  collection:
  cupertino_icons:
  flutter:
    sdk: flutter
  flutter_confetti:
  flutter_riverpod:
  freezed_annotation:
  gap:
  json_annotation:
  json_serializable:
  riverpod_annotation:
  roggle:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_gen_runner:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  freezed:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/assets/
